           - name: Azure WebApp
  uses: Azure/webapps-deploy@v3.0.1    
  with:
    # Name of the Azure Web App
    app-name: 
    # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
    publish-profile: # optional
    # Enter an existing Slot other than the Production slot
    slot-name: # optional, default is production
    # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
    package: # optional, default is .
    # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
    images: # optional
    # Applies to Web App Containers only: Path of the Docker-Compose file. Should be a fully qualified path or relative to the default working directory. Required for multi-container scenario
    configuration-file: # optional
    # Enter the start up command. For ex. dotnet run or dotnet run
    startup-command: # optional
    # Enter the resource group name of the web app
    resource-group-name: # optional
    # Enter deployment type (JAR, WAR, EAR, ZIP, Static)
    type: # optional
    # Target path in the web app. For ex. '/home/site/wwwroot'
    target-path: # optional
    # Delete existing files target directory before deploying
    clean: # optional
    # Restart the app service after deployment
    restart: # optional
   - name: Azure Login
  uses: Azure/login@v1.5.1
  with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
    creds: # optional
    # ClientId of the Azure Service principal created.
    client-id: # optional
    # TenantId of the Azure Service principal created.
    tenant-id: # optional
    # Azure subscriptionId
    subscription-id: # optional
    # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
    enable-AzPSSession: # optional
    # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
    environment: # optional, default is azurecloud
    # Set this value to true to enable support for accessing tenants without subscriptions
    allow-no-subscriptions: # optional
    # Provide audience field for access-token. Default value is api://AzureADTokenExchange
    audience: # optional, default is api://AzureADTokenExchange
    # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
    auth-type: # optional, default is SERVICE_PRINCIPAL
            - name: Microsoft Azure Container Registry Login
  # You may pin to the exact commit or the version.
  # uses: elgohr/acr-login-action@b088ef4d7c3847f3c14159b968860890482003fa
  uses: elgohr/acr-login-action@0.1
  with:
    # The ACR service principal to use for login
    service_principal: 
    # The password of the service principal
    service_principal_password: 
    # The ACR tenant to use for login
    tenant: 
    # The ACR registry to use
    registry: 
    # The ACR repository to use
    repository: 
          
